#icarus project
version: "3.3"
services:
  back:
    image: icarus/code-node:14
    ports:
      - "9080:8080"
      #- "8888:5000"
    environment:
      PASSWORD: 123
      REPO: git@github.com:codelrond78/icarus.back.py.git
      GIT_USER: codelrond
      GIT_USER_EMAIL: codelrond@protonmail.com
      BRANCH: dev
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - settings:/root/.local/share/code-server
      - vback:/app
      - /var/run/docker.sock:/var/run/docker.sock
  front:
    image: icarus/code-node:14
    ports:
      - "9081:8080"
      - "5000:5000"
    environment:
      PASSWORD: 123
      REPO: git@github.com:codelrond78/icarus.front.git
      GIT_USER: codelrond
      GIT_USER_EMAIL: codelrond@protonmail.com
      BRANCH: dev
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - settings:/root/.local/share/code-server
      - vfront:/app
      - /var/run/docker.sock:/var/run/docker.sock
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: 123
volumes:
    vfront:
    vback:
    settings:
      external: true
