# dev project calculadora solar rs
version: "3.3"
services:
  backend:
    image: icarus/code-rust-python
    ports:
      - "8080:8080"
    environment:
      REPO: git@github.com:codelrond78/solar-rs.git
      GIT_USER: codelrond
      GIT_USER_EMAIL: codelrond@protonmail.com
      BRANCH: dev
      PASSWORD: "123"
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - settings:/root/.local/share/code-server
      - /mnt/chromeos/removable/ssd/dev/workspaces/icarus-rs:/app
      #- /var/run/docker.sock:/var/run/docker.sock
volumes:
    #vcalculadorasolarfrontend:
    #vcalculadorasolarbackend:
    settings:
      external: true